export STREAM_URL="http://localhost:8080/dashboard/stream"
export CORS_ORIGINS="http://localhost:8081/api/order"
export STORE_ID="ATLANTA"
export PGSQL_URL="jdbc:postgresql://localhost:5432/coffeeshopdb?currentSchema=coffeeshop"
export PGSQL_USER="coffeeshopuser"
export PGSQL_PASSWORD="redhat-21"
export PGSQL_USER_KITCHEN="coffeeshopuser"
export PGSQL_PASSWORD_KITCHEN="redhat-21"
export PGSQL_URL_BARISTA="jdbc:postgresql://localhost:5432/coffeeshopdb?currentSchema=barista"
export PGSQL_URL_KITCHEN="jdbc:postgresql://localhost:5432/coffeeshopdb?currentSchema=kitchen"
export PGSQL_USER_BARISTA="coffeeshopuser"
export PGSQL_PASSWORD_BARISTA="redhat-21"

